
module.exports = [
  {name: "TheNow" },
  {name: "KERO" },
  {name: "KGTV" },
  {name: "KGUN" },
  {name: "KIVI" },
  {name: "KJRH" },
  {name: "KMGH" },
  {name: "KMTV" },
  {name: "KNXV" },
  {name: "KSAW" },
  {name: "KSHB" },
  {name: "KTNV" },
  {name: "WCPO" },
  {name: "WEWS" },
  {name: "WFTS" },
  {name: "WFTX" },
  {name: "WGBA" },
  {name: "WKBW" },
  {name: "WMAR" },
  {name: "WPTV" },
  {name: "WRTV" },
  {name: "WSYM" },
  {name: "WTMJ" },
  {name: "WTVF" },
  {name: "WXYZ" },
  {name: "Graphics HUB" },
  {name: "TheList" },
  {name: "Newsy" },
  {name: "DWYM" },
  {name: "PolitiFact" },
  {name: "DC Bureau" },
  {name: "Scripps" },
]